### ISSUE TITLE
not work correctly on VR （use OpenXR + HMD mook)

### ISSUE THREAD

**Issue by SnowWindSaveYou** [happy-turtle/oit-unity#6]
only the bottom about 1/10 part of screen can seen the oit result

**Comment by SnowWindSaveYou** [comment]
ok i fixed this problem, 
the buffer size was too small, just increase it by multiply 4

**Comment by happy-turtle** [comment]
Nice, I am surprised it works at all in VR. Image effects are usually problematic on VR with Unity.
